version: '3.9'

services:
  web:
    build: .
    container_name: flowershop_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - bot

  bot:
    build: .
    container_name: flowershop_bot
    command: python bot_app/main.py
    volumes:
      - .:/app
    env_file:
      - .env
