# Generated by Django 5.1.7 on 2025-03-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='bouquets/')),
                ('is_active', models.BooleanField(default=True)),
                ('occasion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='shop_bouque_is_acti_8ec4be_idx'), models.Index(fields=['occasion'], name='shop_bouque_occasio_f4f4b4_idx'), models.Index(fields=['price'], name='shop_bouque_price_37598c_idx')],
            },
        ),
    ]
