# Generated by Django 5.1.7 on 2025-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bouquets/'),
        ),
    ]
