# Generated by Django 5.1.7 on 2025-03-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_testupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUpload',
        ),
    ]
